- hosts: all
  roles:
    - role: geerlingguy.mysql
      become: yes
      vars:
        # We must first create a dbuser@localhost before we can
        # grant remote privileges below.
          mysql_users:
            - name: dbuser
              host: localhost
              password: secret
              priv: "*.*:ALL"
          # Grants user remote access from any ip address.
            - name: dbuser
              host: '%'
              password: secret
              priv: "*.*:ALL,GRANT"
        # Databases
          mysql_databases:
            - name: db1
              collation: utf8_general_ci
              encoding: utf8
              replicate: 1

  tasks:
    - name: Install mySql cli client on guest OS
      apt:
        name: "{{ item }}"
        state: present
        update-cache: yes
      loop:
        - mysql-client-core-5.7
        - mysql-client-5.7
